stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: registry.gitlab.com
  IMAGE_NAME: $CI_REGISTRY_IMAGE

build_image:
  stage: build
  image: docker:26
  services:
    - docker:26-dind
  script:
    - echo ">>> Docker login to GitLab Registry"
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo ">>> Build docker image"
    - docker build -t "$IMAGE_NAME:latest" .
    - echo ">>> Push docker image"
    - docker push "$IMAGE_NAME:latest"
  only:
    - main
