name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USER }}/mentoring

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build docker image
        run: docker build --platform=linux/amd64 -t "$IMAGE_NAME:latest" .

      - name: Push docker image
        run: docker push "$IMAGE_NAME:latest"

